<?php

namespace hipanel\rbac\tests\unit;

use hipanel\rbac\AuthManager;
use hipanel\rbac\Initer;
use Yii;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-08 at 11:38:52.
 */
class AuthManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AuthManager
     */
    protected $auth;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->auth = Yii::createObject([
            'class'             => AuthManager::class,
            'itemFile'          => '@hipanel/rbac/tests/items.php',
            'ruleFile'          => '@hipanel/rbac/tests/rules.php',
            'assignmentFile'    => '@hipanel/rbac/tests/assignments.php',
        ]);
        Initer::reinit($this->auth);

        $this->auth->setAssignment('manager', 'test');
        $this->auth->setAssignment('freezer', 'test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testMin()
    {
        $this->assertTrue($this->auth->checkAccess('test', 'domainSetNSs'));
        $this->assertTrue($this->auth->checkAccess('test', 'support'));
        $this->assertTrue($this->auth->checkAccess('test', 'manage'));
        $this->assertTrue($this->auth->checkAccess('test', 'freeze'));
        $this->assertTrue($this->auth->checkAccess('test', 'unfreeze'));

        $this->assertFalse($this->auth->checkAccess('test', 'administer'));
        $this->assertFalse($this->auth->checkAccess('test', 'deposit'));
    }
}
